import { DEFAULT_KOSTENPROFIEL } from "./calc";
import type {
  Chauffeur,
  DocumentItem,
  OnderhoudAlert,
  Stop,
  TransportOrder,
  Voertuig,
} from "./types";

let stopSeq = 0;
export function stop(partial: Partial<Stop> & { type: Stop["type"] }): Stop {
  stopSeq += 1;
  return {
    id: `stop-${stopSeq}`,
    bedrijfsnaam: "",
    straat: "",
    huisnummer: "",
    postcode: "",
    plaats: "",
    land: "Nederland",
    contactpersoon: "",
    telefoon: "",
    datum: "",
    tijdVan: "",
    tijdTot: "",
    referentie: "",
    instructies: "",
    ...partial,
  };
}

export const DEMO_VOERTUIGEN: Voertuig[] = [
  {
    id: "v-42bfh3",
    kenteken: "42-BFH-3",
    type: "trekker",
    omschrijving: "Trekker DAF XF",
    chauffeurNaam: "R. Peters",
    kmStand: 312480,
    status: "In gebruik",
    kostenprofiel: { ...DEFAULT_KOSTENPROFIEL },
    routingProfiel: {
      hoogteM: 3.95,
      breedteM: 2.55,
      lengteM: 16.5,
      gewichtKg: 40000,
      assen: 5,
      emissieklasse: "Euro 6",
      co2Klasse: "1",
      truckProfile: "EUR_TRAILER_TRUCK",
    },
  },
  {
    id: "v-vx88kl",
    kenteken: "VX-88-KL",
    type: "trekker",
    omschrijving: "Trekker Scania R450",
    chauffeurNaam: "M. de Wit",
    kmStand: 198220,
    status: "In gebruik",
    kostenprofiel: { ...DEFAULT_KOSTENPROFIEL, dieselverbruikPer100km: 29 },
    routingProfiel: {
      hoogteM: 3.9,
      breedteM: 2.55,
      lengteM: 16.5,
      gewichtKg: 40000,
      assen: 5,
      emissieklasse: "Euro 6",
      co2Klasse: "1",
      truckProfile: "EUR_TRAILER_TRUCK",
    },
  },
  {
    id: "v-tr04",
    kenteken: "TR-04",
    type: "trailer",
    omschrijving: "Trailer huifzeil",
    chauffeurNaam: "—",
    kmStand: 0,
    status: "Beschikbaar",
  },
  {
    id: "v-tr07",
    kenteken: "TR-07",
    type: "trailer",
    omschrijving: "Trailer koel",
    chauffeurNaam: "—",
    kmStand: 0,
    status: "Onderhoud",
  },
];

export const DEMO_CHAUFFEURS: Chauffeur[] = [
  { id: "c-peters", naam: "R. Peters", rijbewijs: "CE", code95TotJaar: 2027, urenDezeWeek: 38.5 },
  { id: "c-dewit", naam: "M. de Wit", rijbewijs: "CE", code95TotJaar: 2026, urenDezeWeek: 41.0 },
  { id: "c-alain", naam: "Alain (zelf)", rijbewijs: "CE", code95TotJaar: 2028, urenDezeWeek: 22.0 },
];

export const DEMO_ONDERHOUD: OnderhoudAlert[] = [
  {
    id: "oh-1",
    kenteken: "42-BFH-3",
    titel: "APK verloopt",
    omschrijving:
      "APK moet uitgevoerd worden, maar er staan transportorders gepland rond deze datum. Operationeel conflict: voertuig is ingeplleand op DO-2201.",
    ernst: "conflict",
    verwacht: "APK-datum valt binnen geplande ritten",
  },
  {
    id: "oh-2",
    kenteken: "VX-88-KL",
    titel: "Voorbanden vervangen",
    omschrijving: "Voorspelling op basis van km-gebruik: voorbanden aan vervanging toe.",
    ernst: "waarschuwing",
    verwacht: "± 6 weken / rond 215.000 km",
  },
  {
    id: "oh-3",
    kenteken: "TR-07",
    titel: "Onderhoud koelunit",
    omschrijving: "Koelunit-onderhoud gepland — trailer staat in de werkplaats.",
    ernst: "waarschuwing",
    verwacht: "Gepland / in werkplaats",
  },
  {
    id: "oh-4",
    kenteken: "42-BFH-3",
    titel: "Periodiek onderhoud",
    omschrijving: "Periodieke onderhoudsbeurt op basis van km-voorspelling.",
    ernst: "info",
    verwacht: "± 4 weken / rond 320.000 km",
  },
];

export const DEMO_ORDERS: TransportOrder[] = [
  {
    id: "DO-2201",
    status: "Gepland",
    klant: "Peka Kroef",
    contactpersoon: "S. Jansen",
    klantreferentie: "PK-88213",
    eigenReferentie: "DO-2201",
    orderdatum: "2026-08-20",
    uitvoeringsdatum: "2026-08-21",
    vertrek: "Wijchen, Nederland",
    eind: "Wijchen, Nederland",
    stops: [
      stop({
        type: "laden",
        bedrijfsnaam: "Peka Kroef",
        straat: "Doornhoek",
        huisnummer: "4040",
        postcode: "5466 TD",
        plaats: "Veghel",
        land: "Nederland",
        contactpersoon: "S. Jansen",
        telefoon: "+31 413 000 000",
        datum: "2026-08-21",
        tijdVan: "07:00",
        tijdTot: "08:00",
        referentie: "PK-88213",
        instructies: "Gekoeld laden, temperatuur 2-4 °C.",
      }),
      stop({
        type: "lossen",
        bedrijfsnaam: "HANOS Zwolle",
        straat: "Schokkerweg",
        huisnummer: "9",
        postcode: "8042 PC",
        plaats: "Zwolle",
        land: "Nederland",
        contactpersoon: "Receptie expeditie",
        telefoon: "+31 38 000 000",
        datum: "2026-08-21",
        tijdVan: "11:00",
        tijdTot: "12:30",
        referentie: "HAN-4471",
        instructies: "Aanmelden bij poort 3, CMR laten aftekenen.",
      }),
    ],
    lading: {
      omschrijving: "Verse gekoelde groenten",
      gewichtKg: 12400,
      pallets: 18,
      laadmeters: 10.4,
      bijzonderheden: "Temperatuurgevoelig",
    },
    materieel: { chauffeurId: "c-peters", trekkerId: "v-42bfh3", trailerId: "v-tr07" },
    commercieel: {
      verkoopprijs: 750,
      toeslagen: 0,
      korting: 0,
      btwPct: 21,
      betalingsconditie: "30 dagen",
    },
    truckProfile: "EUR_TRAILER_TRUCK",
    route: {
      km: 268,
      drivingMinutes: 232,
      tollEuro: 0,
      aanrijKm: 42,
      beladenKm: 137,
      terugKm: 89,
      source: "PTV",
      berekendOp: "2026-08-20",
      legs: [
        { from: "Wijchen, Nederland", to: "Peka Kroef, Veghel", km: 42, minutes: 36 },
        { from: "Peka Kroef, Veghel", to: "HANOS Zwolle", km: 137, minutes: 112 },
        { from: "HANOS Zwolle", to: "Wijchen, Nederland", km: 89, minutes: 84 },
      ],
    },
    overrides: {},
    offertedatum: "2026-08-18",
  },
  {
    id: "DO-2202",
    status: "Te factureren",
    klant: "Bakker Logistiek",
    contactpersoon: "J. Bakker",
    klantreferentie: "BL-2026-334",
    eigenReferentie: "DO-2202",
    orderdatum: "2026-08-17",
    uitvoeringsdatum: "2026-08-19",
    vertrek: "Arnhem, Nederland",
    eind: "Nijmegen, Nederland",
    stops: [
      stop({
        type: "laden",
        bedrijfsnaam: "Bakker Logistiek",
        straat: "Westervoortsedijk",
        huisnummer: "73",
        postcode: "6827 AV",
        plaats: "Arnhem",
        contactpersoon: "J. Bakker",
        telefoon: "+31 26 000 000",
        datum: "2026-08-19",
        tijdVan: "09:00",
        tijdTot: "10:00",
        referentie: "BL-2026-334",
      }),
      stop({
        type: "lossen",
        bedrijfsnaam: "Distributiecentrum Nijmegen",
        straat: "Bijsterhuizen",
        huisnummer: "2400",
        postcode: "6604 LL",
        plaats: "Nijmegen",
        contactpersoon: "Expeditie",
        telefoon: "+31 24 000 000",
        datum: "2026-08-19",
        tijdVan: "12:00",
        tijdTot: "13:00",
        referentie: "DCN-9910",
      }),
    ],
    lading: {
      omschrijving: "Gestapelde pallets droge lading",
      gewichtKg: 4200,
      pallets: 8,
      laadmeters: 4.8,
      bijzonderheden: "",
    },
    materieel: { chauffeurId: "c-dewit", trekkerId: "v-vx88kl", trailerId: "v-tr04" },
    commercieel: {
      verkoopprijs: 260,
      toeslagen: 0,
      korting: 0,
      btwPct: 21,
      betalingsconditie: "14 dagen",
    },
    truckProfile: "EUR_TRAILER_TRUCK",
    route: {
      km: 46,
      drivingMinutes: 52,
      tollEuro: 0,
      source: "PTV",
      berekendOp: "2026-08-17",
      legs: [
        { from: "Arnhem, Nederland", to: "Bakker Logistiek, Arnhem", km: 6, minutes: 9 },
        { from: "Bakker Logistiek, Arnhem", to: "DC Nijmegen", km: 27, minutes: 28 },
        { from: "DC Nijmegen", to: "Nijmegen, Nederland", km: 13, minutes: 15 },
      ],
    },
    overrides: {},
    nacalculatie: { werkelijkeKm: 51, werkelijkeTijdMin: 205, werkelijkeKosten: 168 },
  },
  {
    id: "DO-2203",
    status: "Concept",
    klant: "Van Dijk Groente & Fruit",
    contactpersoon: "P. van Dijk",
    klantreferentie: "",
    eigenReferentie: "DO-2203",
    orderdatum: "2026-08-20",
    uitvoeringsdatum: "2026-08-24",
    vertrek: "Wijchen, Nederland",
    eind: "Wijchen, Nederland",
    stops: [
      stop({
        type: "laden",
        bedrijfsnaam: "Van Dijk Groente & Fruit",
        straat: "Handelsweg",
        huisnummer: "12",
        postcode: "6602 DL",
        plaats: "Wijchen",
        datum: "2026-08-24",
        tijdVan: "06:30",
        tijdTot: "07:30",
      }),
      stop({
        type: "lossen",
        bedrijfsnaam: "Foodmarkt Eindhoven",
        straat: "Kanaaldijk",
        huisnummer: "24",
        postcode: "5642 CB",
        plaats: "Eindhoven",
        datum: "2026-08-24",
        tijdVan: "10:00",
        tijdTot: "11:00",
      }),
    ],
    lading: {
      omschrijving: "Groente en fruit",
      gewichtKg: 8600,
      pallets: 12,
      laadmeters: 7.2,
      bijzonderheden: "Gekoeld 4 °C",
    },
    materieel: { chauffeurId: null, trekkerId: null, trailerId: null },
    commercieel: {
      verkoopprijs: 0,
      toeslagen: 0,
      korting: 0,
      btwPct: 21,
      betalingsconditie: "30 dagen",
    },
    truckProfile: "EUR_TRAILER_TRUCK",
    overrides: {},
  },
  {
    id: "DO-2204",
    status: "Onderweg",
    klant: "Coldstore Twente",
    contactpersoon: "H. Wolters",
    klantreferentie: "CT-7712",
    eigenReferentie: "DO-2204",
    orderdatum: "2026-08-19",
    uitvoeringsdatum: "2026-08-20",
    vertrek: "Wijchen, Nederland",
    eind: "Hengelo, Nederland",
    stops: [
      stop({
        type: "laden",
        bedrijfsnaam: "Coldstore Twente",
        straat: "Vosboerweg",
        huisnummer: "8",
        postcode: "7554 RJ",
        plaats: "Hengelo",
        datum: "2026-08-20",
        tijdVan: "08:00",
        tijdTot: "09:00",
      }),
      stop({
        type: "tussenstop",
        bedrijfsnaam: "Tankstation A1",
        straat: "A1",
        huisnummer: "—",
        postcode: "",
        plaats: "Deventer",
        datum: "2026-08-20",
        tijdVan: "10:00",
        tijdTot: "10:20",
      }),
      stop({
        type: "lossen",
        bedrijfsnaam: "Versgroothandel Apeldoorn",
        straat: "Laan van Westenenk",
        huisnummer: "100",
        postcode: "7336 AZ",
        plaats: "Apeldoorn",
        datum: "2026-08-20",
        tijdVan: "12:00",
        tijdTot: "13:00",
      }),
    ],
    lading: {
      omschrijving: "Diepvriesproducten",
      gewichtKg: 15200,
      pallets: 22,
      laadmeters: 12.6,
      bijzonderheden: "-18 °C",
    },
    materieel: { chauffeurId: "c-alain", trekkerId: "v-42bfh3", trailerId: "v-tr04" },
    commercieel: {
      verkoopprijs: 640,
      toeslagen: 35,
      korting: 0,
      btwPct: 21,
      betalingsconditie: "30 dagen",
    },
    truckProfile: "EUR_TRAILER_TRUCK",
    route: {
      km: 214,
      drivingMinutes: 186,
      tollEuro: 0,
      source: "PTV",
      berekendOp: "2026-08-19",
    },
    overrides: {},
  },
];

export const DEMO_DOCUMENTEN: DocumentItem[] = [
  {
    id: "doc-1",
    naam: "Offerte DO-2201",
    soort: "Offerte",
    orderId: "DO-2201",
    datum: "2026-08-18",
    herkomst: "Afgeleid van order",
  },
  {
    id: "doc-2",
    naam: "Ritopdracht DO-2201",
    soort: "Ritopdracht",
    orderId: "DO-2201",
    datum: "2026-08-20",
    herkomst: "Afgeleid van order",
  },
  {
    id: "doc-3",
    naam: "Factuurvoorstel DO-2202",
    soort: "Factuurvoorstel",
    orderId: "DO-2202",
    datum: "2026-08-19",
    herkomst: "Afgeleid van order",
  },
];
