/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BoekhoudingRouteImport } from './routes/boekhouding'
import { Route as ChauffeursRouteImport } from './routes/chauffeurs'
import { Route as DocumentenRouteImport } from './routes/documenten'
import { Route as FactuurvoorstellenRouteImport } from './routes/factuurvoorstellen'
import { Route as KostenRendementRouteImport } from './routes/kosten-rendement'
import { Route as MissionControlRouteImport } from './routes/mission-control'
import { Route as OnderhoudRouteImport } from './routes/onderhoud'
import { Route as PlanningRouteImport } from './routes/planning'
import { Route as RitcalculatorRouteImport } from './routes/ritcalculator'
import { Route as TransportordersIndexRouteImport } from './routes/transportorders.index'
import { Route as TransportordersOrderIdRouteImport } from './routes/transportorders.$orderId'
import { Route as VoertuigenIndexRouteImport } from './routes/voertuigen.index'
import { Route as VoertuigenVoertuigIdRouteImport } from './routes/voertuigen.$voertuigId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BoekhoudingRoute = BoekhoudingRouteImport.update({
  id: '/boekhouding',
  path: '/boekhouding',
  getParentRoute: () => rootRouteImport,
} as any)
const ChauffeursRoute = ChauffeursRouteImport.update({
  id: '/chauffeurs',
  path: '/chauffeurs',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentenRoute = DocumentenRouteImport.update({
  id: '/documenten',
  path: '/documenten',
  getParentRoute: () => rootRouteImport,
} as any)
const FactuurvoorstellenRoute = FactuurvoorstellenRouteImport.update({
  id: '/factuurvoorstellen',
  path: '/factuurvoorstellen',
  getParentRoute: () => rootRouteImport,
} as any)
const KostenRendementRoute = KostenRendementRouteImport.update({
  id: '/kosten-rendement',
  path: '/kosten-rendement',
  getParentRoute: () => rootRouteImport,
} as any)
const MissionControlRoute = MissionControlRouteImport.update({
  id: '/mission-control',
  path: '/mission-control',
  getParentRoute: () => rootRouteImport,
} as any)
const OnderhoudRoute = OnderhoudRouteImport.update({
  id: '/onderhoud',
  path: '/onderhoud',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanningRoute = PlanningRouteImport.update({
  id: '/planning',
  path: '/planning',
  getParentRoute: () => rootRouteImport,
} as any)
const RitcalculatorRoute = RitcalculatorRouteImport.update({
  id: '/ritcalculator',
  path: '/ritcalculator',
  getParentRoute: () => rootRouteImport,
} as any)
const TransportordersIndexRoute = TransportordersIndexRouteImport.update({
  id: '/transportorders/',
  path: '/transportorders/',
  getParentRoute: () => rootRouteImport,
} as any)
const TransportordersOrderIdRoute = TransportordersOrderIdRouteImport.update({
  id: '/transportorders/$orderId',
  path: '/transportorders/$orderId',
  getParentRoute: () => rootRouteImport,
} as any)
const VoertuigenIndexRoute = VoertuigenIndexRouteImport.update({
  id: '/voertuigen/',
  path: '/voertuigen/',
  getParentRoute: () => rootRouteImport,
} as any)
const VoertuigenVoertuigIdRoute = VoertuigenVoertuigIdRouteImport.update({
  id: '/voertuigen/$voertuigId',
  path: '/voertuigen/$voertuigId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/boekhouding': typeof BoekhoudingRoute
  '/chauffeurs': typeof ChauffeursRoute
  '/documenten': typeof DocumentenRoute
  '/factuurvoorstellen': typeof FactuurvoorstellenRoute
  '/kosten-rendement': typeof KostenRendementRoute
  '/mission-control': typeof MissionControlRoute
  '/onderhoud': typeof OnderhoudRoute
  '/planning': typeof PlanningRoute
  '/ritcalculator': typeof RitcalculatorRoute
  '/transportorders/$orderId': typeof TransportordersOrderIdRoute
  '/voertuigen/$voertuigId': typeof VoertuigenVoertuigIdRoute
  '/transportorders/': typeof TransportordersIndexRoute
  '/voertuigen/': typeof VoertuigenIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/boekhouding': typeof BoekhoudingRoute
  '/chauffeurs': typeof ChauffeursRoute
  '/documenten': typeof DocumentenRoute
  '/factuurvoorstellen': typeof FactuurvoorstellenRoute
  '/kosten-rendement': typeof KostenRendementRoute
  '/mission-control': typeof MissionControlRoute
  '/onderhoud': typeof OnderhoudRoute
  '/planning': typeof PlanningRoute
  '/ritcalculator': typeof RitcalculatorRoute
  '/transportorders/$orderId': typeof TransportordersOrderIdRoute
  '/voertuigen/$voertuigId': typeof VoertuigenVoertuigIdRoute
  '/transportorders': typeof TransportordersIndexRoute
  '/voertuigen': typeof VoertuigenIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/boekhouding': typeof BoekhoudingRoute
  '/chauffeurs': typeof ChauffeursRoute
  '/documenten': typeof DocumentenRoute
  '/factuurvoorstellen': typeof FactuurvoorstellenRoute
  '/kosten-rendement': typeof KostenRendementRoute
  '/mission-control': typeof MissionControlRoute
  '/onderhoud': typeof OnderhoudRoute
  '/planning': typeof PlanningRoute
  '/ritcalculator': typeof RitcalculatorRoute
  '/transportorders/$orderId': typeof TransportordersOrderIdRoute
  '/voertuigen/$voertuigId': typeof VoertuigenVoertuigIdRoute
  '/transportorders/': typeof TransportordersIndexRoute
  '/voertuigen/': typeof VoertuigenIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/boekhouding'
    | '/chauffeurs'
    | '/documenten'
    | '/factuurvoorstellen'
    | '/kosten-rendement'
    | '/mission-control'
    | '/onderhoud'
    | '/planning'
    | '/ritcalculator'
    | '/transportorders/$orderId'
    | '/voertuigen/$voertuigId'
    | '/transportorders/'
    | '/voertuigen/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/boekhouding'
    | '/chauffeurs'
    | '/documenten'
    | '/factuurvoorstellen'
    | '/kosten-rendement'
    | '/mission-control'
    | '/onderhoud'
    | '/planning'
    | '/ritcalculator'
    | '/transportorders/$orderId'
    | '/voertuigen/$voertuigId'
    | '/transportorders'
    | '/voertuigen'
  id:
    | '__root__'
    | '/'
    | '/boekhouding'
    | '/chauffeurs'
    | '/documenten'
    | '/factuurvoorstellen'
    | '/kosten-rendement'
    | '/mission-control'
    | '/onderhoud'
    | '/planning'
    | '/ritcalculator'
    | '/transportorders/$orderId'
    | '/voertuigen/$voertuigId'
    | '/transportorders/'
    | '/voertuigen/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BoekhoudingRoute: typeof BoekhoudingRoute
  ChauffeursRoute: typeof ChauffeursRoute
  DocumentenRoute: typeof DocumentenRoute
  FactuurvoorstellenRoute: typeof FactuurvoorstellenRoute
  KostenRendementRoute: typeof KostenRendementRoute
  MissionControlRoute: typeof MissionControlRoute
  OnderhoudRoute: typeof OnderhoudRoute
  PlanningRoute: typeof PlanningRoute
  RitcalculatorRoute: typeof RitcalculatorRoute
  TransportordersOrderIdRoute: typeof TransportordersOrderIdRoute
  VoertuigenVoertuigIdRoute: typeof VoertuigenVoertuigIdRoute
  TransportordersIndexRoute: typeof TransportordersIndexRoute
  VoertuigenIndexRoute: typeof VoertuigenIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/boekhouding': {
      id: '/boekhouding'
      path: '/boekhouding'
      fullPath: '/boekhouding'
      preLoaderRoute: typeof BoekhoudingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chauffeurs': {
      id: '/chauffeurs'
      path: '/chauffeurs'
      fullPath: '/chauffeurs'
      preLoaderRoute: typeof ChauffeursRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documenten': {
      id: '/documenten'
      path: '/documenten'
      fullPath: '/documenten'
      preLoaderRoute: typeof DocumentenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/factuurvoorstellen': {
      id: '/factuurvoorstellen'
      path: '/factuurvoorstellen'
      fullPath: '/factuurvoorstellen'
      preLoaderRoute: typeof FactuurvoorstellenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kosten-rendement': {
      id: '/kosten-rendement'
      path: '/kosten-rendement'
      fullPath: '/kosten-rendement'
      preLoaderRoute: typeof KostenRendementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mission-control': {
      id: '/mission-control'
      path: '/mission-control'
      fullPath: '/mission-control'
      preLoaderRoute: typeof MissionControlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onderhoud': {
      id: '/onderhoud'
      path: '/onderhoud'
      fullPath: '/onderhoud'
      preLoaderRoute: typeof OnderhoudRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planning': {
      id: '/planning'
      path: '/planning'
      fullPath: '/planning'
      preLoaderRoute: typeof PlanningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ritcalculator': {
      id: '/ritcalculator'
      path: '/ritcalculator'
      fullPath: '/ritcalculator'
      preLoaderRoute: typeof RitcalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transportorders/': {
      id: '/transportorders/'
      path: '/transportorders'
      fullPath: '/transportorders/'
      preLoaderRoute: typeof TransportordersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transportorders/$orderId': {
      id: '/transportorders/$orderId'
      path: '/transportorders/$orderId'
      fullPath: '/transportorders/$orderId'
      preLoaderRoute: typeof TransportordersOrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/voertuigen/': {
      id: '/voertuigen/'
      path: '/voertuigen'
      fullPath: '/voertuigen/'
      preLoaderRoute: typeof VoertuigenIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/voertuigen/$voertuigId': {
      id: '/voertuigen/$voertuigId'
      path: '/voertuigen/$voertuigId'
      fullPath: '/voertuigen/$voertuigId'
      preLoaderRoute: typeof VoertuigenVoertuigIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BoekhoudingRoute: BoekhoudingRoute,
  ChauffeursRoute: ChauffeursRoute,
  DocumentenRoute: DocumentenRoute,
  FactuurvoorstellenRoute: FactuurvoorstellenRoute,
  KostenRendementRoute: KostenRendementRoute,
  MissionControlRoute: MissionControlRoute,
  OnderhoudRoute: OnderhoudRoute,
  PlanningRoute: PlanningRoute,
  RitcalculatorRoute: RitcalculatorRoute,
  TransportordersOrderIdRoute: TransportordersOrderIdRoute,
  VoertuigenVoertuigIdRoute: VoertuigenVoertuigIdRoute,
  TransportordersIndexRoute: TransportordersIndexRoute,
  VoertuigenIndexRoute: VoertuigenIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
